# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'skeleton_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pathlib


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(270, 20, 251, 61))
        font = QtGui.QFont()
        font.setFamily("Javanese Text")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.searchBar = QtWidgets.QLineEdit(self.centralwidget)
        self.searchBar.setGeometry(QtCore.QRect(220, 120, 351, 31))
        self.searchBar.setText("")
        self.searchBar.setObjectName("searchBar")
        self.subTitle = QtWidgets.QLabel(self.centralwidget)
        self.subTitle.setGeometry(QtCore.QRect(280, 90, 221, 20))
        font = QtGui.QFont()
        font.setFamily("Javanese Text")
        font.setPointSize(9)
        self.subTitle.setFont(font)
        self.subTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.subTitle.setObjectName("subTitle")
        self.searchButton = QtWidgets.QPushButton(self.centralwidget)
        self.searchButton.setGeometry(QtCore.QRect(360, 160, 75, 23))
        self.searchButton.setObjectName("searchButton")
        self.resultLabel = QtWidgets.QLabel(self.centralwidget)
        self.resultLabel.setGeometry(QtCore.QRect(30, 200, 461, 331))
        font = QtGui.QFont()
        font.setFamily("Javanese Text")
        font.setPointSize(14)
        self.resultLabel.setFont(font)
        self.resultLabel.setText("")
        self.resultLabel.setPixmap(QtGui.QPixmap(str(pathlib.Path().absolute()) + '/assets/raccoon.png').scaled(500, 500, QtCore.Qt.KeepAspectRatio, QtCore.Qt.SmoothTransformation))
        self.resultLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.resultLabel.setObjectName("resultLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.searchButton.clicked.connect(lambda: self.clicked())

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "Twitter Scraper"))
        self.subTitle.setText(_translate("MainWindow", "Enter a Twitter handle below"))
        self.searchButton.setText(_translate("MainWindow", "Search"))

    def clicked(self):
      twitterHandle = self.searchBar.text()
      pixmap = QtGui.QPixmap(str(pathlib.Path().absolute()) + '/assets/red_panda.jpg').scaled(500, 500, QtCore.Qt.KeepAspectRatio, QtCore.Qt.SmoothTransformation)
      self.resultLabel.setPixmap(pixmap)

      print('click complete')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
